name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - if: "(github.actor != 'dependabot[bot]') && !startsWith(github.head_ref, 'dependabot/')"
        name: Check commits
        uses: wagoid/commitlint-github-action@v2
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: npm install
