name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commits-are-conventional:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - if: "(github.actor != 'dependabot[bot]') && !startsWith(github.head_ref, 'dependabot/')"
        name: Check commits
        uses: wagoid/commitlint-github-action@v5

  npm-registry-is-public:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1

      - name: Check
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |-
          set -eEu
          set +o pipefail

          grep -n '"resolved": "' package-lock.json |
          grep -v "https://registry.npmjs.org/" |
          sed -E 's/([0-9]+):[^\:]*:[^\"]*\"([^"]+)\"/package-lock.json:\1:Incorrect npm registry \"\2\". Use npm public registry./'  |
          reviewdog \
            -efm="%f:%l:%m" \
            -name="npm-registry-is-public" \
            -reporter="github-pr-review" \
            -filter-mode="file" \
            -fail-on-error="true" \
            -level="error"
